### ISSUE TITLE
Run Errors

### ISSUE THREAD

**Issue by ghost** [1213-Throwback/Project_2#5]
I have begun to test the test-project2 file. Below is the output from the test I ran before and after making any changes to the test-project2 file. At the moment I believe the only issue is that the template-processor.js file is not complete which I think is causing the errors. 
![unnamed](https://github.com/1213-Throwback/Project_2/assets/112581503/7c469efe-2fa1-4f83-ac59-1e861abb1a61)

**Comment by Vulcran** [comment]
Hey Ryan,
     Looked over the errors and you were right the issues were caused by the incomplete template file. Once I finished it up the results changed to their expected output.
